apiVersion: v1
kind: Service
metadata:
   labels:
      app: db
   name: db
spec:
   type: ClusterIP
   selector:
      matchLabels:
         app: db
   ports:
      - name: "db-service"
        port: 5432
        targetPort: 5432

