apiVersion: v1
kind: Service
metadata:
   labels:
      app: db
   name: db
spec:
   selector:
      matchLabels:
         app: db
   ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
   type: ClusterIP

