apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
      app: result
   name: result
spec:
   replicas: 2
   selector:
      matchLabels: 
          app: result
   template:
       metadata:
           labels:
              app: result
       spec:
          conatiners:
              - image: karthickdocker28/result
                name: result
                ports:
                  - conatinerPort: 80
                    name: result    
