apiVersion: v1
kind: Service
metadata:
    labels:
       app: result
    name: result
spec:
   type: NodePort
   selector:
          app: result
   ports:
      - name: "result-service"
        port: 5001
        targerPort: 80
        nodeport: 31001 
