pipeline {
    agent any 
    environment {
        REPO = 'karthickdocker28'
    }

    stages {
        stage('build vote image') {
            steps {
                sh 'cd myrepo/dovote_app/vote'
                sh 'docker build -t $REPO/vote .'
                sh 'cd ..'
            }
        }
        
        stage('build result image') {
            steps {
                sh 'cd myrepo/dovote_app/result'
                sh 'docker build -t $REPO/result .'
                sh 'cd ..'
            }
        }
        
        stage('build worker image') {
            steps {
                sh 'cd myrepo/dovote_app/worker'
                sh 'docker build -t $REPO/worker .'
                sh 'cd ..'
            }
        }
        
        stage('push vote image') {
            steps {
                withDockerRegistry(credentialsId: 'dockerhub', url: 'dockerbuildbot-index.docker.io') {
                    sh 'docker push $REPO/vote'
                }
            }
        }
        
        stage('push worker image') {
            steps {
                withDockerRegistry(credentialsId: 'dockerhub', url: 'dockerbuildbot-index.docker.io') {
                    sh 'docker push $REPO/worker'
                }
            }
        }
        
        stage('push result image') {
            steps {
                withDockerRegistry(credentialsId: 'dockerhub', url: 'dockerbuildbot-index.docker.io') {
                    sh 'docker push $REPO/result'
                }
            }
        }
    }
}
