pipeline {
    agent any 
    environment {
        REPO = 'karthickdocker28'
    }

    stages {
        stage('build vote image') {
            steps {
                sh 'cd /var/lib/jenkins/workspace/myrepo/dovote_app/vote'
                sh 'docker build -t $REPO/vote .'
            }
        }
        
        stage('build result image') {
            steps {
                sh 'cd /var/lib/jenkins/workspace/myrepo/dovote_app/result'
                sh 'docker build -t $REPO/result .'
                sh 'cd ..'
            }
        }
        
        stage('build worker image') {
            steps {
                sh 'cd /var/lib/jenkins/workspace/myrepo/dovote_app/worker'
                sh 'docker build -t $REPO/worker .'
                sh 'cd ..'
            }
        }
        
        stage('push vote image') {
            steps {
                docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
                    sh 'docker push $REPO/vote'
                }
            }
        }
        
        stage('push worker image') {
            steps {
                docker.withRegistry('https://index.docker.io/v1/',"dockerhub")  {
                    sh 'docker push $REPO/worker'
                }
            }
        }
        
        stage('push result image') {
            steps {
                docker.withRegistry('https://index.docker.io/v1/', "dockerhub") {
                    sh 'docker push $REPO/result'
                }
            }
        }
    }
}
